### PR TITLE
SivaReader: add failing test for updated file content

### PR DESCRIPTION
**Pull request by bzz**
A new test case and fixtures for pin-pointing a 🐞  on reading updated file content.
**CI is expected to fail**

All details are in #5

### CODE REVIEW

**Comment by bzz** [comment]
CI failed as expected
```
[info] - should change if the file has been appended *** FAILED ***
[info]   116 was not equal to 8 (SivaReaderSpec.scala:112)
```

This PR can be merged asap, and then fix can be built on top of it, in a separate PR.

**Comment by bzz** [comment]
@ajnavarro do you think we can merge this guy now and push fix in a subsequent PR?

**Comment by ajnavarro** [comment]
@bzz I prefer to have the fix and the test passing on the same PR. Does not make sense add to master a failing test, for that we have issues. I will commit to this PR adding the fix.

**Comment by ajnavarro** [comment]
The PR content is in https://github.com/src-d/siva-java/pull/6 . Closing this in favor of https://github.com/src-d/siva-java/pull/6

**Pull request closed without merging**
